# MCU name

MCU = STM32F103

MCU_LDSCRIPT = STM32F103xB_maplemini_bootloader

BOARD = goose60v1

BOOTLOADER = custom

BOOTMAGIC_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes

AUTO_SHIFT_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
COMBO_ENABLE = no
AUDIO_ENABLE = no
ENCODER_ENABLE = no
KEY_LOCK_ENABLE = no
MOUSEKEY_ENABLE = yes

OLED_ENABLE = no

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDEL=TRUE

DEBOUNCE_TYPE = sym_defer_g

CUSTOM_MATRIX = yes

SRC += matrix.c
